### PR TITLE
Inbox mail filter added

### LINKED ISSUE #15: Selecting email messages crashes the app
I'm not sure if this is related, but after syncing an account, I then synced an email from the remote peer and selected the new message on mobile. This immediately crashed the app.

### PR DESCRIPTION
**Pull request by suleymancelikel**

### CODE REVIEW

File: src/store/mail.ts [hunk 1]
```diff
@@ -362,12 +389,13 @@ export const mailSlice = createSlice({
...
   reducers: {
     fileFetched: (state, action: PayloadAction<FileFetchedPayload>) => {
-      const email = {
-        ...action.payload.email.content,
-        _id: action.payload._id,
-        bodyAsText: action.payload.email.content.text_body,
-        bodyAsHTML: action.payload.email.content.html_body,
-      };
+      const email = action.payload;
+      // const email = {
```
Comment (vitalikgriza) [inline src/store/mail.ts]: Please remove commented lines
